### ISSUE TITLE
Module '@testing-library/react' has no exported member 'fireEvent'.

### ISSUE THREAD

**Issue by Mikilll94** [reduxjs/cra-template-redux-typescript#34]
I have found a bug.

Here are steps to reproduce
1. Create a new project using `cra-template-redux-typescript`
2. Go to `App.test.tsx`
3. Try to import `fireEvent` from `@testing-library/react`
4. VSCode shows an error `Module '@testing-library/react' has no exported member 'fireEvent'.`

![Screenshot 2021-03-16 at 23 24 18](https://user-images.githubusercontent.com/17653648/111387880-bbe96a00-86ae-11eb-8e58-2d1f49d4eafd.png)

Repro project:
[redux-ts-test.zip](https://github.com/reduxjs/cra-template-redux-typescript/files/6152550/redux-ts-test.zip)

It's worth noting that this bug does not exist in official CRA templates: `cra-template` and `cra-template-typescript`

**Comment by loralridz** [comment]
Your issue seems to be related with packages update as the current template generated using _**cra-template-redux-typescript**_ gives us outdated packages. 
- Either you can update your packages using npm
- Or wait for this PR to get merged [template packages update PR](https://github.com/reduxjs/cra-template-redux-typescript/pull/43)

**Comment by markerikson** [comment]
Should resolved with https://github.com/reduxjs/cra-template-redux-typescript/releases/tag/v2.0.0 .
